/**
 * Account collection configuration. Defines the categories of accounts
 * the app will help the user secure, in priority order, and the known
 * services within each category.
 *
 * Each service includes identifiers for auto-mode (Bitwarden CLI saves
 * the URL and/or iOS/Android app IDs alongside the credentials).
 *
 * Categories are presented to the user one at a time. Within each
 * category, the user can select which services they use and enter
 * credentials for each.
 */

export const ACCOUNT_CATEGORIES = Object.freeze([
  {
    id: 'essential',
    name: 'Essential accounts',
    description: 'Your email, internet banking, and phone provider.',
    services: [
      {
        id: 'email',
        name: 'Email',
        icon: 'envelope',
        placeholder: 'e.g. Gmail, Outlook, ProtonMail',
        url: '',
        ios: '',
        android: '',
        customUrl: true,
      },
      {
        id: 'banking',
        name: 'Internet banking',
        icon: 'money',
        placeholder: 'e.g. Chase, HSBC, NatWest',
        url: '',
        ios: '',
        android: '',
        customUrl: true,
      },
      {
        id: 'phone',
        name: 'Phone provider',
        icon: 'phone',
        placeholder: 'e.g. Verizon, EE, Vodafone',
        url: '',
        ios: '',
        android: '',
        customUrl: true,
      },
    ],
  },
  {
    id: 'social',
    name: 'Social media',
    description: 'Your social media accounts.',
    services: [
      {
        id: 'facebook',
        name: 'Facebook',
        favicon: true,
        url: 'https://facebook.com',
        ios: 'id284882215',
        android: 'com.facebook.katana',
      },
      {
        id: 'instagram',
        name: 'Instagram',
        favicon: true,
        url: 'https://instagram.com',
        ios: 'id389801252',
        android: 'com.instagram.android',
      },
      {
        id: 'x',
        name: 'X (Twitter)',
        favicon: true,
        url: 'https://x.com',
        ios: 'id333903271',
        android: 'com.twitter.android',
      },
      {
        id: 'linkedin',
        name: 'LinkedIn',
        favicon: true,
        url: 'https://linkedin.com',
        ios: 'id288429040',
        android: 'com.linkedin.android',
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        favicon: true,
        url: 'https://tiktok.com',
        ios: 'id835599320',
        android: 'com.zhiliaoapp.musically',
      },
      {
        id: 'snapchat',
        name: 'Snapchat',
        favicon: true,
        url: 'https://snapchat.com',
        ios: 'id833635796',
        android: 'com.snapchat.android',
      },
      {
        id: 'pinterest',
        name: 'Pinterest',
        favicon: true,
        url: 'https://pinterest.com',
        ios: 'id429047995',
        android: 'com.pinterest',
      },
      {
        id: 'reddit',
        name: 'Reddit',
        favicon: true,
        url: 'https://reddit.com',
        ios: 'id1064216828',
        android: 'com.reddit.frontpage',
      },
      {
        id: 'mastodon',
        name: 'Mastodon',
        favicon: true,
        url: 'https://mastodon.social',
        ios: 'id1571998974',
        android: 'org.joinmastodon.android',
      },
      {
        id: 'threads',
        name: 'Threads',
        favicon: true,
        url: 'https://threads.net',
        ios: 'id6446901002',
        android: 'com.instagram.barcelona',
      },
      {
        id: 'bluesky',
        name: 'Bluesky',
        favicon: true,
        url: 'https://bsky.app',
        ios: 'id6444310139',
        android: 'xyz.blueskyweb.app',
      },
    ],
  },
  {
    id: 'chat-gaming',
    name: 'Social chat & gaming',
    description: 'Your messaging and gaming platform accounts.',
    services: [
      {
        id: 'whatsapp',
        name: 'WhatsApp',
        favicon: true,
        url: 'https://whatsapp.com',
        ios: 'id310633997',
        android: 'com.whatsapp',
      },
      {
        id: 'telegram',
        name: 'Telegram',
        favicon: true,
        url: 'https://telegram.org',
        ios: 'id686449807',
        android: 'org.telegram.messenger',
      },
      {
        id: 'signal',
        name: 'Signal',
        favicon: true,
        url: 'https://signal.org',
        ios: 'id878139776',
        android: 'org.thoughtcrime.securesms',
      },
      {
        id: 'discord',
        name: 'Discord',
        favicon: true,
        url: 'https://discord.com',
        ios: 'id985446889',
        android: 'com.discord',
      },
      {
        id: 'twitch',
        name: 'Twitch',
        favicon: true,
        url: 'https://twitch.tv',
        ios: 'id460177130',
        android: 'tv.twitch.android.app',
      },
      {
        id: 'steam',
        name: 'Steam',
        favicon: true,
        url: 'https://store.steampowered.com',
        ios: '',
        android: 'com.valvesoftware.android.steam.community',
      },
      {
        id: 'playstation',
        name: 'PlayStation',
        favicon: true,
        url: 'https://playstation.com',
        ios: 'id410896080',
        android: 'com.scee.psxandroid',
      },
      {
        id: 'nintendo',
        name: 'Nintendo',
        favicon: true,
        url: 'https://nintendo.com',
        ios: 'id1236803280',
        android: 'com.nintendo.znca',
      },
      {
        id: 'epic-games',
        name: 'Epic Games',
        favicon: true,
        url: 'https://epicgames.com',
        ios: 'id1238932640',
        android: 'com.epicgames.portal',
      },
    ],
  },
  {
    id: 'subscriptions',
    name: 'Subscriptions',
    description: 'Streaming and subscription services.',
    services: [
      {
        id: 'spotify',
        name: 'Spotify',
        favicon: true,
        url: 'https://spotify.com',
        ios: 'id324684580',
        android: 'com.spotify.music',
      },
      {
        id: 'netflix',
        name: 'Netflix',
        favicon: true,
        url: 'https://netflix.com',
        ios: 'id363590051',
        android: 'com.netflix.mediaclient',
      },
      {
        id: 'amazon-prime',
        name: 'Amazon Prime Video',
        favicon: true,
        url: 'https://primevideo.com',
        ios: 'id545419333',
        android: 'com.amazon.avod.thirdpartyclient',
      },
      {
        id: 'disney-plus',
        name: 'Disney+',
        favicon: true,
        url: 'https://disneyplus.com',
        ios: 'id1446075948',
        android: 'com.disney.disneyplus',
      },
      {
        id: 'youtube',
        name: 'YouTube',
        favicon: true,
        url: 'https://youtube.com',
        ios: 'id544007664',
        android: 'com.google.android.youtube',
      },
      {
        id: 'apple-music',
        name: 'Apple Music',
        favicon: true,
        url: 'https://music.apple.com',
        ios: 'id1108187390',
        android: 'com.apple.android.music',
      },
      {
        id: 'binge',
        name: 'Binge',
        favicon: true,
        url: 'https://binge.com.au',
        ios: 'id1502699523',
        android: 'com.foxtel.binge',
      },
      {
        id: 'stan',
        name: 'Stan',
        favicon: true,
        url: 'https://stan.com.au',
        ios: 'id966841353',
        android: 'au.com.stan.android',
      },
      {
        id: 'paramount-plus',
        name: 'Paramount+',
        favicon: true,
        url: 'https://paramountplus.com',
        ios: 'id1493944548',
        android: 'com.cbs.app.paramountplus',
      },
      {
        id: 'kayo',
        name: 'Kayo Sports',
        favicon: true,
        url: 'https://kayosports.com.au',
        ios: 'id1240957132',
        android: 'au.com.kayosports',
      },
      {
        id: 'abc-iview',
        name: 'ABC iView',
        favicon: true,
        url: 'https://iview.abc.net.au',
        ios: 'id313121767',
        android: 'au.net.abc.iview',
      },
      {
        id: 'sbs-on-demand',
        name: 'SBS On Demand',
        favicon: true,
        url: 'https://sbs.com.au/ondemand',
        ios: 'id579081331',
        android: 'com.sbs.ondemand',
      },
      {
        id: '9now',
        name: '9Now',
        favicon: true,
        url: 'https://9now.com.au',
        ios: 'id815907906',
        android: 'com.nine.nownow',
      },
      {
        id: '7plus',
        name: '7plus',
        favicon: true,
        url: 'https://7plus.com.au',
        ios: 'id898502621',
        android: 'com.yahoo.mobile.client.android.kids',
      },
      {
        id: '10-play',
        name: '10 Play',
        favicon: true,
        url: 'https://10play.com.au',
        ios: 'id411426932',
        android: 'com.cbsinteractive.tenplay',
      },
    ],
  },
]);

/**
 * Supported manual-mode import formats. Each entry maps to a generator
 * function in the import-generator script, and includes the password
 * manager's website URL and step-by-step import instructions.
 */
export const IMPORT_FORMATS = Object.freeze([
  {
    id: 'bitwarden-csv',
    label: 'Bitwarden (CSV)',
    extension: 'csv',
    websiteUrl: 'https://bitwarden.com',
    importSteps: [
      'Open the Bitwarden web vault at vault.bitwarden.com',
      'Go to Tools → Import data',
      'Select "Bitwarden (csv)" as the file format',
      'Choose the file you just downloaded',
      'Click Import data',
    ],
  },
  {
    id: 'bitwarden-json',
    label: 'Bitwarden (JSON)',
    extension: 'json',
    websiteUrl: 'https://bitwarden.com',
    importSteps: [
      'Open the Bitwarden web vault at vault.bitwarden.com',
      'Go to Tools → Import data',
      'Select "Bitwarden (json)" as the file format',
      'Choose the file you just downloaded',
      'Click Import data',
    ],
  },
  {
    id: '1password-csv',
    label: '1Password (CSV)',
    extension: 'csv',
    websiteUrl: 'https://1password.com',
    importSteps: [
      'Open 1Password in your browser at start.1password.com',
      'Click your account name → Import',
      'Select "Other" as the category',
      'Choose the CSV file you just downloaded',
      'Click Import',
    ],
  },
  {
    id: 'protonpass-csv',
    label: 'Proton Pass (CSV)',
    extension: 'csv',
    websiteUrl: 'https://proton.me/pass',
    importSteps: [
      'Open Proton Pass in your browser at pass.proton.me',
      'Go to Settings → Import',
      'Select the CSV file you just downloaded',
      'Click Import to load your accounts',
    ],
  },
  {
    id: 'lastpass-csv',
    label: 'LastPass (CSV)',
    extension: 'csv',
    websiteUrl: 'https://lastpass.com',
    importSteps: [
      'Open LastPass in your browser at lastpass.com',
      'Go to Account Options → Advanced → Import',
      'Select "LastPass" as the source',
      'Choose the CSV file you just downloaded',
      'Click Import to load your accounts',
    ],
  },
]);
